# Generated by Django 3.2.5 on 2021-08-31 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='cases',
            field=models.TextField(default=12, verbose_name='用例'),
            preserve_default=False,
        ),
    ]
