# Generated by Django 3.2.5 on 2021-08-31 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0002_task_cases'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.IntegerField(default=0, verbose_name='请求方法'),
        ),
    ]
