# Generated by Django 3.2.5 on 2021-08-31 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='assert_text',
            field=models.TextField(null=True, verbose_name='断言'),
        ),
        migrations.AlterField(
            model_name='case',
            name='assert_type',
            field=models.IntegerField(null=True, verbose_name='断言类型'),
        ),
        migrations.AlterField(
            model_name='case',
            name='header',
            field=models.TextField(null=True, verbose_name='请求头'),
        ),
        migrations.AlterField(
            model_name='case',
            name='method',
            field=models.IntegerField(null=True, verbose_name='请求方法'),
        ),
        migrations.AlterField(
            model_name='case',
            name='parameter_body',
            field=models.TextField(null=True, verbose_name='参数内容'),
        ),
        migrations.AlterField(
            model_name='case',
            name='parameter_type',
            field=models.IntegerField(null=True, verbose_name='参数类型'),
        ),
        migrations.AlterField(
            model_name='case',
            name='result_body',
            field=models.TextField(null=True, verbose_name='结果'),
        ),
    ]
